Class Task 3

A = np.array([[2, -1], [0, 3]])
B = np.array([[1, 4], [-2, 5]])

c = 2
d = 3



Compute the following: (cA), (dB), and (c+d)A

cA where:

A = np.array([[2, -1] [0, 3]])
c = 2

[[2.2 2.(-1)], [2.0  2.3]]
[[4 -2][0 6]]


cA = np.array([[4 -2],
                [0 6]])

dB where 

B = np.array([[1, 4] [-2, 5]])
d = 3

[[3.1 3.4], [3.(-2)  3.5]]
[[3 12][-6 15]]

dB = np.array([[3 12]
                [-6 15]])

(c+d)A where:

c = 2
d = 3
A = np.array([[2, -1] [0, 3]])

step 1:
c + d = 2 + 3 =5

step 2: multiply array A by c+d (5)
[[5.2 5.(-1)], [5.0  5.3]]
[[10 -5],[0 15]]

c + d(A) = np.array([[10 -5],
                    [0 15]])



## Question B

Using the resullt gotten, verify the scaler multiplication properties

1. Associativity

cA where:
A = np.array([[2, -1] [0, 3]])
c = 2

prove that cA = Ac

cA = [[2.2 2.(-1)], 
      [2.0  2.3]]
[[4 -2],[0 6]]


cA = np.array([[4 -2],
                [0 6]])

Ac = [[2, -1] [0, 3]] x 2
[[2.2, -1(2)] [0.2, 3.2]]

Ac = np.array([[4 -2],
                [0 6]])

cA == Ac  proving the associativity property of scaler multiplication

Associativity
dB where 

B = np.array([[1, 4] [-2, 5]])
d = 3

[[3.1 3.4], [3.(-2)  3.5]]
[[3 12][-6 15]]

dB = np.array([[3 12]
                [-6 15]])


dB = [[1, 4] [-2, 5]] x 3
[[1.3 4.3] [-2.3 5.3]]

Bd = np.array([[3 12], 
                [-6 15]])

dB == Bd thereby proving the associativity property of scaler multiplication

Distributivity over scaler Addition

(c+d)A == cA + dA where:

c = 2
d = 3
A = np.array([[2, -1] [0, 3]])

step 1:
c + d = 2 + 3 =5

step 2: multiply array A by c+d (5)
[[5.2 5.(-1)], [5.0  5.3]]
[[10 -5],[0 15]]

c + d(A) = np.array([[10 -5],
                    [0 15]])

where cA:
c = 2
A = np.array([[2, -1] [0, 3]])

[[2.2, 2(-1)] [2.0 2.3]]
cA = np.array([[4 -2],
                [0 6]])


where dA:
d = 3
A = np.array([[2, -1] [0, 3]])

[[2, -1] [0, 3]] x 3

[[3.2 3(-1)] [3.0 3.3]]
dA =np.array([[6, -3], 
               [0, 9]])

cA + dA where:

cA = np.array([[4 -2],
                [0 6]])

dA =np.array([[6, -3], 
               [0, 9]])

cA + dA = np.array([[10, -5], 
                    [0 15]])

from the foregoing (c+d)A == cA + dA  thereby proving the distributivity over scaler addition 




Question 3

In [ ]:
find the transpose of the below transpose

A = np.array([[2, -1] [0, 3]])
B = np.array([[1, 4] [-2, 5]])

where:
A = np.array([[2, -1] 
                [0, 3]])
AT = np.array([[2 0], 
                [-1 3]])

where:
B = np.array([[1, 4], 
            [-2, 5]])

BT = np.array([[1 -2], 
                [4 5]])

