## Student Performance Analysis with Linear Algebra

In [6]:
import numpy as np

1. Create a new 5×4 matrix of scores (5 students, 4 subjects). Compute each student’s total
score and the average per subject.


In [7]:
# Creating sudent data
"""
students            Maths               English             Science             Literature
Student1             90                    70                  50                   60
Student2             70                    25                  65                   72
Student3             85                    88                  90                   87
Student4             75                    80                  65                   77
Student5             40                    31                  55                   44

"""



student1 = np.array([90, 70, 50, 60])
student2 = np.array([70, 25, 65, 72])
student3 = np.array([85, 88, 90, 87])
student4 = np.array([75, 80, 65, 77])
student5 = np.array([40, 31, 55, 44])



students_data = np.array([[90, 70, 50, 60],  
                          [70, 25, 65, 72],
                          [85, 88, 90, 87],
                          [75, 80, 65, 77],
                          [40, 31, 55, 44]])

# calculate student1 total score
student1_total_score = np.sum(students_data[0, :])
print("Student1 Total Score:", student1_total_score)

# calculate student2 total score
student2_total_score = np.sum(students_data[1, :])
print("Student2 Total Score:", student2_total_score)

# calculate student3 total score
student3_total_score = np.sum(students_data[2, :])
print("Student3 Total Score:", student3_total_score)

# calculate student4 total score
student4_total_score = np.sum(students_data[3, :])
print("Student4 Total Score:", student4_total_score)


# calculate student5 total score
student5_total_score = np.sum(students_data[4, :])
print("Student5 Total Score:", student5_total_score)

Student1 Total Score: 270
Student2 Total Score: 232
Student3 Total Score: 350
Student4 Total Score: 297
Student5 Total Score: 170


In [8]:
students_data

array([[90, 70, 50, 60],
       [70, 25, 65, 72],
       [85, 88, 90, 87],
       [75, 80, 65, 77],
       [40, 31, 55, 44]])

In [9]:
# Students Average per Subject

maths = np.sum(students_data[:, 0])
print("Maths Total score:", maths)

english = np.sum(students_data[:, 1])
print("English Total score:", english)

science = np.sum(students_data[:, 2])
print("Science Total score:", science)

literature = np.sum(students_data[:, 2])
print("Literature Total score:", literature)



Maths Total score: 360
English Total score: 294
Science Total score: 325
Literature Total score: 325


In [11]:
students_data

array([[90, 70, 50, 60],
       [70, 25, 65, 72],
       [85, 88, 90, 87],
       [75, 80, 65, 77],
       [40, 31, 55, 44]])

In [12]:
"""
students            Maths               English             Science             Literature
Student1             90                    70                  50                   60
Student2             70                    25                  65                   72
Student3             85                    88                  90                   87
Student4             75                    80                  65                   77
Student5             40                    31                  55                   44

"""

'\nstudents            Maths               English             Science             Literature\nStudent1             90                    70                  50                   60\nStudent2             70                    25                  65                   72\nStudent3             85                    88                  90                   87\nStudent4             75                    80                  65                   77\nStudent5             40                    31                  55                   44\n\n'

In [13]:
# Average Score for all subject

# 1. Average score for Mathematics
maths_average_score = np.sum(students_data[:, 0]) / len(students_data[:, 0])
print("Maths average score is:", maths_average_score)

# 2. Average score for English
eng_average_score = np.sum(students_data[:, 1]) / len(students_data[:, 1])
print("English average score is:", eng_average_score)

# 3. Average score for Science
science_average_score = np.sum(students_data[:, 2]) / len(students_data[:, 2])
print("Science average score is:", science_average_score)

# 4. Average score for literature
lit_average_score = np.sum(students_data[:, 3]) / len(students_data[:, 3])
print("Literature average score is:", science_average_score)

Maths average score is: 72.0
English average score is: 58.8
Science average score is: 65.0
Literature average score is: 65.0


In [14]:
# Applying Scaler Weight to score
# if other subjects score is 2, Science is thrice of them which is 6

# computing scaler scores
scalar_weight = np.array([6, 2, 2, 2 ])
print("The scalar weight is:", scalar_weight)

# adding scalar weight to student data matrix
students_data_with_scalar = students_data * scalar_weight
print("Student score multiplied by scalar weight is: ", students_data_with_scalar)

The scalar weight is: [6 2 2 2]
Student score multiplied by scalar weight is:  [[540 140 100 120]
 [420  50 130 144]
 [510 176 180 174]
 [450 160 130 154]
 [240  62 110  88]]
