Question 1

In [2]:
import numpy as np

In [6]:
A = np.array([[2, -1], 
            [0, 3]])
B = np.array([[1, 4], 
            [-2, 5]])

c = 2
d = 3


In [9]:
# Compute the following: (cA), (dB), and (c+d)A

# cA where:
c = 2
A = np.array([[2, -1], [0, 3]])

cA = np.dot(c, A)
print("cA equals:\n", cA)

cA equals:
 [[ 4 -2]
 [ 0  6]]


In [ ]:
# dB where 
d = 3
B = np.array([[1, 4], [-2, 5]])


dB = np.dot(d, B)
print("dB equals:\n", dB)



dB equals:
 [[ 3 12]
 [-6 15]]


In [ ]:
# (c+d)A where:

c = 2
d = 3
A = np.array([[2, -1], [0, 3]])

# step 1:
c_plus_d = c + d
print("c + d:", c_plus_d)

# step 2: multiply array A by c+d (5)
c_plus_d = c + d
A = np.array([[2, -1], [0, 3]])
c_plus_d_times_A = np.dot(c_plus_d, A)
print("c + d(A):\n", c_plus_d_times_A)


c + d: 5
c + d(A):
 [[10 -5]
 [ 0 15]]


Question B

Using the resullt gotten, verify the scaler multiplication properties

1. Associativity of scaler multiplication

In [23]:
# cA where:
c = 2
A = np.array([[2, -1], [0, 3]])

print("c:", c)
print("A:\n", A)

# prove that cA = Ac

cA =np.dot(c, A)
print("c multiply A:\n", cA)

Ac = np.dot(A, c)
print("c multiply A:\n", cA)

left = c * A
right = A * c

print(f"Associative: {np.array_equal(left, right)}")

# cA == Ac  proving the associativity property of scaler multiplication

c: 2
A:
 [[ 2 -1]
 [ 0  3]]
c multiply A:
 [[ 4 -2]
 [ 0  6]]
c multiply A:
 [[ 4 -2]
 [ 0  6]]
Associative: True


In [24]:
# Associativity
# dB where 
d = 3
B = np.array([[1, 4], [-2, 5]])


print("d:", d)
print("B:\n", B)

dB = np.dot(d, B)


# prove that dB = Bd

cA =np.dot(d, B)
print("d multiply B:\n", dB)

Ac = np.dot(d, B)
print("d multiply B:\n", dB)

left = d * B
right = B * d

print(f"Associative: {np.array_equal(left, right)}")


# dB == Bd thereby proving the associativity property of scaler multiplication

d: 3
B:
 [[ 1  4]
 [-2  5]]
d multiply B:
 [[ 3 12]
 [-6 15]]
d multiply B:
 [[ 3 12]
 [-6 15]]
Associative: True


In [26]:
# Distributivity over scaler Addition

# (c+d)A == cA + dAwhere:

c = 2
d = 3
A = np.array([[2, -1], [0, 3]])
print("c:", c)
print("d:", d)
print("A:\n", A)

# step 1:  find cA 

c_times_A = np.dot(c, A)
print("c multiplies by A: \n", c_times_A)
 
# step 2: find  dA

d_times_A = np.dot(d, A)
print("d multiplies by A: \n", d_times_A)

# step 3: cA + dA

cA_plus_dA = c_times_A + d_times_A
print("cA plus dA:\n", cA_plus_dA)


# step 4: prove that  c + d(A) == cA(dA)


c_plus_d_times_A = np.dot(c_plus_d, A)
print("c + d(A):\n", c_plus_d_times_A)


left = c + d * A
right = c * A + d * A

print(f"Distributive: {np.array_equal(left, right)}")

# from the foregoing (c+d)A == cA + dA  thereby proving the distributivity over scaler addition 

c: 2
d: 3
A:
 [[ 2 -1]
 [ 0  3]]
c multiplies by A: 
 [[ 4 -2]
 [ 0  6]]
d multiplies by A: 
 [[ 6 -3]
 [ 0  9]]
cA plus dA:
 [[10 -5]
 [ 0 15]]
c + d(A):
 [[10 -5]
 [ 0 15]]
Distributive: False
