Class Task 3

A = np.array([[2, -1] [0, 3]])
B = np.array([[1, 4] [-2, 5]])

c = 2
d = 3



Compute the following: (cA), (dB), and (c+d)A

cA where:

A = np.array([[2, -1] [0, 3]])
c = 2

[[2.2 2.(-1)], [2.0  2.3]]
[[4 -2][0 6]]


cA = np.array([[4 -2][0 6]])

dB where 

B = np.array([[1, 4] [-2, 5]])
d = 3

[[3.1 3.4], [3.(-2)  3.5]]
[[3 12][-6 15]]

dB = np.array([[3 12][-6 15]])

(c+d)A where:

c = 2
d = 3
A = np.array([[2, -1] [0, 3]])

step 1:
c + d = 2 + 3 =5

step 2: multiply array A by c+d (5)
[[5.2 5.(-1)], [5.0  5.3]]
[[10 -5][0 15]]

c + d(A) = np.array([[10 -5][0 15]])



## Question B

Using the resullt goten, verify the scaler multiplication properties