In [8]:
# INTRODUCTION TO NUMPY 
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# check NmPy version
print(f"Numpy version: {np.__version__}")

# display settings for cleaner output

np.set_printoptions(precision=3, suppress=True)

Numpy version: 2.3.2


In [10]:
# creating Numpy Array
# 1D array: a simple sequence of numbers
arr1d = np.array([1,2,3,4,5])

# 2D array: think of it as a matrix or table with rows and cols
arr2d = np.array([[1,2,3],
                [4,5,6]])

# 3D array: Like a stack off 2D arrays - useful for images, time series e.t.c
arr3d = np.array([[[1,2], [3,4],],
                  [[5,6], [7,8]]])

print("1D array:", arr1d)
print("2D array:\n:", arr2d)
print("3D array:\n:", arr3d)

1D array: [1 2 3 4 5]
2D array:
: [[1 2 3]
 [4 5 6]]
3D array:
: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
# Creating Special Arrays in Numpy

# crating arrays filled with zero - useful for initilizing arrays
# shape (3,4) means 3rows and 4cols
zeros = np.zeros((3,4))

# creatign arrays filled with ones
ones = np.ones((2,3,4))  #3D array: 2layers, 3rows and 4cols

# empty array - faster than zeros and ones but contains ramdom values
# use when you will immediately fill the array wih real data
empty = np.empty((2,2))

print("Zeros array (3x4):\n", zeros)
print("Ones array shape:", ones.shape)
print("Empty array (contains random values):\n", empty)

Zeros array (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array shape: (2, 3, 4)
Empty array (contains random values):
 [[0. 0.]
 [0. 0.]]


In [15]:
# Range arrays - like Pyhton range() but more power

range_arr = np.arange(0,10,2)   #start, stop, step
print("Range array:", range_arr)


# linearly spaced arrays- divide a range into equal parts
# from 0 to 1 with exactly 5point (including endpooints)

linspace_arr = np.linspace(0,1,5)
print(linspace_arr)

# loagrithmically spaced arrays - useful for scientific data
# from 10^0 to 10^2 (1 o 100) with points
logspace_arr = np.logspace(0,2,5)
print("Logspace array:", logspace_arr)


Range array: [0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
Logspace array: [  1.      3.162  10.     31.623 100.   ]


In [20]:
# Identity matrix  - diagonal of ones, zeros elsewhere
# Essential for linear algebra operation
identity = np.eye(4)
print("Identity matrix:\n", identity)
# Diagonal matrix - put values on the diagonal
diagonal = np.diag([1,2,3,4])
print("Diagonal matrix:\n", diagonal)

# Array filled with a specific value
full_arr = np.full((3,3),7)   #3*3 array fille with 7
print("Full array (filled with 7):\n", full_arr)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Full array (filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [26]:
# NUMPY DATA TYPES
int_arr = np.array([1,2,3], dtype=np.int32)   #32BI INTEGER
float_arr = np.array([1,2,3], dtype=np.float64)  #644bit float
bool_arr = np.array([True, False, True], dtype=np.bool_)  #boolean values
print("Integer array dtype:", int_arr.dtype)
print("Float array dtype:", float_arr.dtype)
print("Boolean array dtype:", bool_arr.dtype)


# Type conversion - change dtype of existing array


converted = int_arr.astype(np.float32)   #convert to 32bt float
print(converted.dtype)


#Memory usage comparison
print(f"int32 uses {int_arr.itemsize} byte per element")
print(f"float64 uses {float_arr.itemsize} byte per element")


Integer array dtype: int32
Float array dtype: float64
Boolean array dtype: bool
float32
int32 uses 4 byte per element
float64 uses 8 byte per element


In [ ]:
#ARRAY PROPERIES AND ATTRBUTES
# understanding array properties helps you work effectively with your data and debug issue

# create a simple 3D array for demonstration 
# think of this as 3 layer, each with 4 rows and 5 cols

arr = np.random.randn(2, 6, 5)      #2layers, 6cols and 5rows


# shape: the dimensions of thr array (layers, rows, col)
print("Shape", arr.shape)

# Size: Total number of elements (3 × 4 × 5 = 60)
print("Size:", arr.size)

# NDim: Number of dimensions (3D inn this case)
print("Ndim:", arr.ndim)

# Dtype: Data type element
print("Dtype:", arr.dtype)

-m 

array([[[ 0.346, -0.244, -0.546,  0.504,  0.746],
        [ 0.818, -0.221,  2.423, -0.176,  0.192],
        [-0.624, -0.088, -1.178, -0.156,  0.54 ],
        [ 1.202,  1.533,  1.588, -0.244,  0.082],
        [ 1.709, -1.36 ,  0.669, -1.111, -0.167],
        [-0.687, -0.366, -0.467,  0.998,  0.581]],

       [[-1.418,  1.317,  0.332, -0.147, -0.974],
        [ 1.562, -0.371, -1.305, -0.56 ,  0.372],
        [ 0.24 , -0.776, -0.123,  0.568, -0.757],
        [-0.231,  0.638, -0.169,  1.981, -1.137],
        [-0.018,  0.132,  0.268,  0.155,  0.911],
        [-1.022,  0.249, -0.154, -2.096,  1.494]]])