In [1]:
# INTRODUCTION TO NUMPY 
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# check NmPy version
print(f"Numpy version: {np.__version__}")

# display settings for cleaner output

np.set_printoptions(precision=3, suppress=True)

Numpy version: 2.3.2


In [2]:
# creating Numpy Array
# 1D array: a simple sequence of numbers
arr1d = np.array([1,2,3,4,5])

# 2D array: think of it as a matrix or table with rows and cols
arr2d = np.array([[1,2,3],
                [4,5,6]])

# 3D array: Like a stack off 2D arrays - useful for images, time series e.t.c
arr3d = np.array([[[1,2], [3,4],],
                  [[5,6], [7,8]]])

print("1D array:", arr1d)
print("2D array:\n:", arr2d)
print("3D array:\n:", arr3d)

1D array: [1 2 3 4 5]
2D array:
: [[1 2 3]
 [4 5 6]]
3D array:
: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
# Creating Special Arrays in Numpy

# crating arrays filled with zero - useful for initilizing arrays
# shape (3,4) means 3rows and 4cols
zeros = np.zeros((3,4))

# creatign arrays filled with ones
ones = np.ones((2,3,4))  #3D array: 2layers, 3rows and 4cols

# empty array - faster than zeros and ones but contains ramdom values
# use when you will immediately fill the array wih real data
empty = np.empty((2,2))

print("Zeros array (3x4):\n", zeros)
print("Ones array shape:", ones.shape)
print("Empty array (contains random values):\n", empty)

Zeros array (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array shape: (2, 3, 4)
Empty array (contains random values):
 [[0. 0.]
 [0. 0.]]


In [4]:
# Range arrays - like Pyhton range() but more power

range_arr = np.arange(0,10,2)   #start, stop, step
print("Range array:", range_arr)


# linearly spaced arrays- divide a range into equal parts
# from 0 to 1 with exactly 5point (including endpooints)

linspace_arr = np.linspace(0,1,5)
print(linspace_arr)

# loagrithmically spaced arrays - useful for scientific data
# from 10^0 to 10^2 (1 o 100) with points
logspace_arr = np.logspace(0,2,5)
print("Logspace array:", logspace_arr)


Range array: [0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
Logspace array: [  1.      3.162  10.     31.623 100.   ]


In [5]:
# Identity matrix  - diagonal of ones, zeros elsewhere
# Essential for linear algebra operation
identity = np.eye(4)
print("Identity matrix:\n", identity)
# Diagonal matrix - put values on the diagonal
diagonal = np.diag([1,2,3,4])
print("Diagonal matrix:\n", diagonal)

# Array filled with a specific value
full_arr = np.full((3,3),7)   #3*3 array fille with 7
print("Full array (filled with 7):\n", full_arr)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Full array (filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [6]:
# NUMPY DATA TYPES
int_arr = np.array([1,2,3], dtype=np.int32)   #32BI INTEGER
float_arr = np.array([1,2,3], dtype=np.float64)  #644bit float
bool_arr = np.array([True, False, True], dtype=np.bool_)  #boolean values
print("Integer array dtype:", int_arr.dtype)
print("Float array dtype:", float_arr.dtype)
print("Boolean array dtype:", bool_arr.dtype)


# Type conversion - change dtype of existing array


converted = int_arr.astype(np.float32)   #convert to 32bt float
print(converted.dtype)


#Memory usage comparison
print(f"int32 uses {int_arr.itemsize} byte per element")
print(f"float64 uses {float_arr.itemsize} byte per element")


Integer array dtype: int32
Float array dtype: float64
Boolean array dtype: bool
float32
int32 uses 4 byte per element
float64 uses 8 byte per element


In [7]:
#ARRAY PROPERIES AND ATTRBUTES
# understanding array properties helps you work effectively with your data and debug issue

# create a simple 3D array for demonstration 
# think of this as 3 layer, each with 4 rows and 5 cols

arr = np.random.randn(2, 6, 5)      #2layers, 6cols and 5rows


# shape: the dimensions of thr array (layers, rows, col)
print("Shape", arr.shape)

# Size: Total number of elements (3 × 4 × 5 = 60)
print("Size:", arr.size)

# NDim: Number of dimensions (3D inn this case)
print("Ndim:", arr.ndim)

# Dtype: Data type element
# print("Dtype:", arr.dtype)

# Itemize: Memory size of each element in byte
print("Itemsize:", arr.itemsize)

# Total size of elements
print("Total size:", arr.nbytes)   #size * itemsize

print("Memory usage:", arr.nbytes / 1024, "KB") #converting bytes to kilobyte

Shape (2, 6, 5)
Size: 60
Ndim: 3
Itemsize: 8
Total size: 480
Memory usage: 0.46875 KB


In [8]:
# ARRAY INDEXING AND SLICING

# bASIC indexing
# numpy indexing is simlar to python list but more powerful for multidimensional arrays

# 1D array indexing - similar to python list
arr1d = np.array([10, 20, 30, 40, 50])

print(arr1d[0])
print(arr1d[-1])
print(arr1d[1:4])
print(arr1d[::2])

10
50
[20 30 40]
[10 30 50]


In [9]:
# Nagative indices count from the end (-1)
# slicing uses [start:stop:step]

# 2d array indexing - row and cols access
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# access specific element: [row, col]
print("Element at row 1, col2:", arr2d[1,2])

print("Element 11:", arr2d[2, 2])

# Access entire rows or cols
print("First row:", arr2d[0, :])
print("Second cols:", arr2d[:, 1])
print("Third col:", arr2d[:, 2])
print("Third row:", arr2d[1, :])

# subarray slicing: [row_start: row_end, col_start:col_end]
print("Subarray (row 1-2, cols 1-2):\n", arr2d[1:3, 1:3])
print(arr2d[1:4, 0:3])

Element at row 1, col2: 7
Element 11: 11
First row: [1 2 3 4]
Second cols: [ 2  6 10]
Third col: [ 3  7 11]
Third row: [5 6 7 8]
Subarray (row 1-2, cols 1-2):
 [[ 6  7]
 [10 11]]
[[ 5  6  7]
 [ 9 10 11]]


In [10]:
# Advance Indexing
arr = np.array([10, 20, 30, 40, 50])
indices =np.array([0, 2, 4])  #to select element at position
print("Fancy Indexing:", arr[indices])  #[10, 30, 50]

# This is more flexible than simple slicing
random_indices = np.array([4, 1, 3, 1])
print("Random order:", arr[random_indices])  #[50, 20, 40, 20]

Fancy Indexing: [10 30 50]
Random order: [50 20 40 20]


In [11]:
# Fancy indexing lets you select elements in any order, repeat element, and 
# selct non-contageous elements. very useful in data sampling and roredering


# 2D fancy indexing -select specific ro/col combination
arr2d = np.arange(12).reshape(3, 4)
print(arr2d)


# select elements at (row,col) pairs: (0,1) and (2,3)
rows = np.array([0, 2])
cols = np.array([1, 3])

print(arr2d[rows, cols])


# select entire rows using fancy indexing
selected_rows= arr2d[[0, 2], :]
print("Selected rows:\n", selected_rows)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1 11]
Selected rows:
 [[ 0  1  2  3]
 [ 8  9 10 11]]


In [12]:
# Start with a 1D array
arr = np.arange(12)  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
print("Original 1D array:", arr)

# Reshape to 2D: 3 rows × 4 columns
reshaped_2d = arr.reshape(3, 4)
print("Reshaped to 3x4:\n", reshaped_2d)

# Reshape to 3D: 2 layers × 2 rows × 3 columns  
reshaped_3d = arr.reshape(2, 2, 3)
print("Reshaped to 2x2x3:\n", reshaped_3d)

# Use -1 to let NumPy calculate one dimension automatically
auto_reshape = arr.reshape(4, -1)  # 4 rows, NumPy calculates columns
print("Auto-reshaped to 4x?:\n", auto_reshape)  #ask

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x2x3:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Auto-reshaped to 4x?:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [13]:
# Flattening - convert multi-dimensional array to 1D
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# flatten() always return a copy
flattened = arr2d.flatten()
print("Flattened (copy):", flattened)

# ravel() returns a view if possible (faster, memory efficient)
ravel = arr2d.ravel()                       
print("Ravel (view if possible):", ravel)

# Demonstrate the difference
arr2d[0, 0] = 999
print("After modifying original:")
print("Flattened (unchanged):", flattened)  # Copy is independent
print("Ravel (changed):", ravel)            # View reflects changes

Flattened (copy): [1 2 3 4 5 6]
Ravel (view if possible): [1 2 3 4 5 6]
After modifying original:
Flattened (unchanged): [1 2 3 4 5 6]
Ravel (changed): [999   2   3   4   5   6]


In [14]:
# TRANSPOSING and SWAPPING AXES
# Transposing is essential for matrix operations and chan

# 2D transpiton - flips row and cols

arr2d = np.array(([1, 2, 3],
                  [4, 5, 6]))

print(arr2d.shape)    #(2, 3)
print(arr2d)
print(arr2d.T)
print(arr2d.T.shape)  #(3,2)


# Alternative transpose methods
print("Transpose method:\n", arr2d.transpose())

(2, 3)
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
(3, 2)
Transpose method:
 [[1 4]
 [2 5]
 [3 6]]


In [15]:
# Higher Dimensional transposition
arr3d = np.arange(24).reshape(2, 3, 4)  # 2 layers, 3 rows, 4 columns
print(arr3d)

# specify new axis order: (axis0, axis1,axis2,) -> (axis2,axis0,axis1)
transpose_3d = arr3d.transpose(2, 0, 1)
transpose_3d

# move axis is anothr way to rearrange axes
moved = np.moveaxis(arr3d, 0, -1)
moved.shape

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


(3, 4, 2)

In [16]:
# Concatenation and Splitting Array
# combining and dividing arrays is fundamental for data manipulation
arr1 = np.array ([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

# concatenation along different axes
concat_rows = np.concatenate([arr1, arr2], axis=0)   # Stack vertically (add rows)
concat_rows
concat_cols = np.concatenate([arr1,arr2], axis=1)   # Stack horizontally (add columns)
concat_cols

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [17]:
# convenient stacking func
arr1 = np.array ([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

vstack_result = np.vstack([arr1, arr2])     #vertical axis(axis=0)
vstack_result
hstack_result = np.hstack([arr1,arr2])     #horizontal axis(axis=1)
hstack_result

dstack_result = np.dstack([arr1, arr2])    #stack into 3dimension
dstack_result.shape




# splitting arrays - Opposite of contenation

arr = np.arange(12).reshape(3,4)
arr


split_arrays = np.split(arr, 3, axis=0)   #this split the array into 3
split_arrays
for i, split_part in enumerate(split_arrays):
    print(f"Part {i}: \n", split_part)

Part 0: 
 [[0 1 2 3]]
Part 1: 
 [[4 5 6 7]]
Part 2: 
 [[ 8  9 10 11]]


In [18]:
# MAth Operations
# Element-wise Operations - The Power of Vectorization
# Basic arithmetic operations work element by element

arr1 = np.array([1,2,3,4,])
arr2 = np.array([10,20,30,40])

arr1 + arr2
arr2 - arr1
arr1 * arr2
arr2 / arr1
arr1 **2
arr2 % 3

array([1, 2, 0, 1])

In [19]:
# Operations with Scaler - broadcasting in action

arr1 = np.array([1,2,3,4,])
arr1 + 10   #adds 10 to all elment in the array
arr1 * 2   #multiply all ekement
arr1 / 2   #divide all element


# Compound Operations
result = (arr1 + 5) * 2-1
result

array([11, 13, 15, 17])

In [20]:
# Maths Funcs - Beyond Basic Arithmetic

arr = np.array([1,4,9,16,25])
arr

# square roots and powers
np.sqrt(arr)     #square root
np.square(arr)      #sauare
np.cbrt(arr)     #cube root


# Exponential and Logic Funcs
small_arr = np.array([1, 2, 3])
np.exp(small_arr)       #exponential
np.log(arr)
np.log10(arr)
np.log2(arr)


array([0.   , 2.   , 3.17 , 4.   , 4.644])

In [21]:
# Trigonometric functions - essential for signal processing and geometry
angles = np.array([0, np.pi/4, np.pi/2, np.pi])
print("Angles (radians):", angles)
print("Sine:", np.sin(angles))                # [0, √2/2, 1, 0]
print("Cosine:", np.cos(angles))              # [1, √2/2, 0, -1]
print("Tangent:", np.tan(angles))             # [0, 1, ∞, 0]

# Convert degrees to radians
degree = np.array([0,45,90,180])
radians = np.deg2rad(degree)
radians


# print(np.pi/4)
# print(np.pi/2)
# print(np.pi)

Angles (radians): [0.    0.785 1.571 3.142]
Sine: [0.    0.707 1.    0.   ]
Cosine: [ 1.     0.707  0.    -1.   ]
Tangent: [ 0.000e+00  1.000e+00  1.633e+16 -1.225e-16]


array([0.   , 0.785, 1.571, 3.142])

In [22]:
# Rounding and comparison functions
decimals = np.array([1.234, 5.678, 9.999, -2.345])
print("Original decimals:", decimals)

np.round(decimals, 2)   #decimal place
np.floor(decimals)      #to round down
np.ceil(decimals)    #rounds up
np.trunc(decimals)      #takes away the decimal num





Original decimals: [ 1.234  5.678  9.999 -2.345]


array([ 1.,  5.,  9., -2.])

In [23]:
# AGGREGATE FUNCS
# It reduces arrays to summary stat
# Create a 2D array for demonstration
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
print("Sample array:\n", arr)

# Aggregation across entire array
print("Sum of all elements:", np.sum(arr))        # 45
print("Mean of all elements:", np.mean(arr))      # 5.0
print("Standard deviation:", np.std(arr))         # 2.58
print("Minimum value:", np.min(arr))              # 1
print("Maximum value:", np.max(arr))              # 9

Sample array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of all elements: 45
Mean of all elements: 5.0
Standard deviation: 2.581988897471611
Minimum value: 1
Maximum value: 9
