In [8]:
# INTRODUCTION TO NUMPY 
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# check NmPy version
print(f"Numpy version: {np.__version__}")

# display settings for cleaner output

np.set_printoptions(precision=3, suppress=True)

Numpy version: 2.3.2


In [10]:
# creating Numpy Array
# 1D array: a simple sequence of numbers
arr1d = np.array([1,2,3,4,5])

# 2D array: think of it as a matrix or table with rows and cols
arr2d = np.array([[1,2,3],
                [4,5,6]])

# 3D array: Like a stack off 2D arrays - useful for images, time series e.t.c
arr3d = np.array([[[1,2], [3,4],],
                  [[5,6], [7,8]]])

print("1D array:", arr1d)
print("2D array:\n:", arr2d)
print("3D array:\n:", arr3d)

1D array: [1 2 3 4 5]
2D array:
: [[1 2 3]
 [4 5 6]]
3D array:
: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
# Creating Special Arrays in Numpy

# crating arrays filled with zero - useful for initilizing arrays
# shape (3,4) means 3rows and 4cols
zeros = np.zeros((3,4))

# creatign arrays filled with ones
ones = np.ones((2,3,4))  #3D array: 2layers, 3rows and 4cols

# empty array - faster than zeros and ones but contains ramdom values
# use when you will immediately fill the array wih real data
empty = np.empty((2,2))

print("Zeros array (3x4):\n", zeros)
print("Ones array shape:", ones.shape)
print("Empty array (contains random values):\n", empty)

Zeros array (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array shape: (2, 3, 4)
Empty array (contains random values):
 [[0. 0.]
 [0. 0.]]


In [15]:
# Range arrays - like Pyhton range() but more power

range_arr = np.arange(0,10,2)   #start, stop, step
print("Range array:", range_arr)


# linearly spaced arrays- divide a range into equal parts
# from 0 to 1 with exactly 5point (including endpooints)

linspace_arr = np.linspace(0,1,5)
print(linspace_arr)

# loagrithmically spaced arrays - useful for scientific data
# from 10^0 to 10^2 (1 o 100) with points
logspace_arr = np.logspace(0,2,5)
print("Logspace array:", logspace_arr)


Range array: [0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
Logspace array: [  1.      3.162  10.     31.623 100.   ]


In [20]:
# Identity matrix  - diagonal of ones, zeros elsewhere
# Essential for linear algebra operation
identity = np.eye(4)
print("Identity matrix:\n", identity)
# Diagonal matrix - put values on the diagonal
diagonal = np.diag([1,2,3,4])
print("Diagonal matrix:\n", diagonal)

# Array filled with a specific value
full_arr = np.full((3,3),7)   #3*3 array fille with 7
print("Full array (filled with 7):\n", full_arr)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Full array (filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
# NUMPY DATA TYPES
int_arr = np.array([1,2,3], dtype=np.int32)   #32BI INTEGER
float_arr = np.array([1,2,3], dtype=np.float64)  #644bit float
bool_arr = np.array([True, False, True], dtype=np.bool_)  #boolean values
print("Integer array dtype:", int_arr.dtype)
print("Float array dtype:", float_arr.dtype)
print("Boolean array dtype:", bool_arr.dtype)


# Type conversion - change dtype of existing array


converted = int_arr.astype(np.float32)   #convert to 32bt float
print(converted.dtype)


#Memory usage comparison
print(f"int32 uses {int_arr.itemsize} byte per element")
print(f"int32 uses {float_arr.itemsize} byte per element")


Integer array dtype: int32
Float array dtype: float64
Boolean array dtype: bool
float32
