In [7]:
import numpy as np


In [ ]:
# Question 1


arr = np.random.randint(1,51, size=(6,6))
# arr_reshape = arr.shape(6,6)
arr

array([[48,  9,  8, 14, 47, 32],
       [47, 32, 14, 13,  3, 25],
       [25, 11, 40, 48, 20,  6],
       [13, 13,  7, 33,  9, 42],
       [43,  3, 19, 45, 42, 17],
       [43, 16, 26, 24, 49, 14]], dtype=int32)

In [43]:
# Question 2

# first two rows
arr[:2, :6]

array([[48,  9,  8, 14, 47, 32],
       [47, 32, 14, 13,  3, 25]], dtype=int32)

In [45]:
# last three cols

arr[:6, 3:]

array([[14, 47, 32],
       [13,  3, 25],
       [48, 20,  6],
       [33,  9, 42],
       [45, 42, 17],
       [24, 49, 14]], dtype=int32)

In [46]:
# all even numbers
divided_by_two = arr[arr%2==0]
divided_by_two

array([48,  8, 14, 32, 32, 14, 40, 48, 20,  6, 42, 42, 16, 26, 24, 14],
      dtype=int32)

In [47]:
# Question 3
arr_reshaped = arr.reshape(3, 2, 6)
arr_reshaped

array([[[48,  9,  8, 14, 47, 32],
        [47, 32, 14, 13,  3, 25]],

       [[25, 11, 40, 48, 20,  6],
        [13, 13,  7, 33,  9, 42]],

       [[43,  3, 19, 45, 42, 17],
        [43, 16, 26, 24, 49, 14]]], dtype=int32)

In [59]:
arr_flatten = arr_reshaped.flatten()
arr_flatten

array([48,  9,  8, 14, 47, 32, 47, 32, 14, 13,  3, 25, 25, 11, 40, 48, 20,
        6, 13, 13,  7, 33,  9, 42, 43,  3, 19, 45, 42, 17, 43, 16, 26, 24,
       49, 14], dtype=int32)

In [84]:
# Question 4

iden_arr = np.eye(4,4)
np.fill_diagonal(iden_arr, np.arange(10,50,10))
iden_arr

array([[10.,  0.,  0.,  0.],
       [ 0., 20.,  0.,  0.],
       [ 0.,  0., 30.,  0.],
       [ 0.,  0.,  0., 40.]])

In [64]:
# Question 5

matrix_one = np.random.randint(1,11, size=(3,4))
matrix_two = np.random.randint(1,11, size=(4,3))
one_times_two = np.dot(matrix_one, matrix_two)
one_times_two

array([[110, 150,  86],
       [ 58, 110,  53],
       [ 51,  46,  45]], dtype=int32)

In [65]:
# Question 6
def two_d_collector(arr):
    result = np.where(arr % 2 ==0, arr**2, -1)
    print(result)

In [87]:
# arr
two_d_collector(arr)

[[2304   -1   64  196   -1 1024]
 [  -1 1024  196   -1   -1   -1]
 [  -1   -1 1600 2304  400   36]
 [  -1   -1   -1   -1   -1 1764]
 [  -1   -1   -1   -1 1764   -1]
 [  -1  256  676  576   -1  196]]


In [73]:
arr2 = np.random.randint(1,31, size=(5,6))
arr2
two_d_collector(arr2)

[[ -1 676  -1  -1  64  -1]
 [144   4  -1 576 576  -1]
 [ -1  -1  -1  -1  -1 256]
 [ -1 484 900 400  -1  -1]
 [256 576  -1 324  -1  -1]]
