In [3]:
import torch
import numpy as np
torch.__version__

'2.9.0+cu126'

In [4]:
arr = np.array(7)
arr.ndim

0

In [6]:
# creating a scaler

scalar = torch.tensor(7)
scalar.ndim

0

In [7]:
# turning tensor to python integer - .item()

scalar.item()

7

In [11]:
# Vector with tensor
vector = torch.tensor([7,7,9])
vector.ndim

1

In [17]:
# Matrix with tensor

matrix = torch.tensor([[2,3], [2,9]])
matrix

tensor([[2, 3],
        [2, 9]])

In [23]:
# Tensor with tensor

tensor = torch.tensor([[[1,2,3], [4,5,6],[7,8,9]]])
tensor.shape

torch.Size([1, 3, 3])

In [25]:
# creating a random tensor of size(3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.7591, 0.3819, 0.2253, 0.6568],
         [0.5160, 0.6926, 0.6241, 0.7090],
         [0.1248, 0.2359, 0.6959, 0.3392]]),
 torch.float32)

In [10]:
# creating a random tensor of size (223, 224, 3)

random_image = torch.rand(size=(224, 224, 3))
random_image.shape, random_image.dtype

(torch.Size([224, 224, 3]), torch.float32)

Zeros and Ones

In [11]:
# ceateing a tensor with only zero values

zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [14]:
# ceateing a tensor with only 1

ones = torch.ones(size=(3,4))
ones, ones.dtype 

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [17]:
# creating a tensor with 1 in the diagonal

one_diag = torch.eye(4)
one_diag

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

CREATING A RANGE and TENSORS LIKE


Where:
* `start` = start of range (e.g. 0)
* `end` = end of range (e.g. 10)
* `step` = how many steps in between each value (e.g. 1)

In [19]:
# creating a range 
range = torch.arange(2,20,3)
range

tensor([ 2,  5,  8, 11, 14, 17])