In [1]:
import torch
import numpy as np
torch.__version__

'2.9.1+cpu'

In [2]:
arr = np.array(7)
arr.ndim

0

In [3]:
# creating a scaler

scalar = torch.tensor(7)
scalar.ndim

0

In [4]:
# turning tensor to python integer - .item()

scalar.item()

7

In [5]:
# Vector with tensor
vector = torch.tensor([7,7,9])
vector.ndim

1

In [6]:
# Matrix with tensor

matrix = torch.tensor([[2,3], [2,9]])
matrix

tensor([[2, 3],
        [2, 9]])

In [7]:
# Tensor with tensor

tensor = torch.tensor([[[1,2,3], [4,5,6],[7,8,9]]])
tensor.shape

torch.Size([1, 3, 3])

In [8]:
# creating a random tensor of size(3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[9.2975e-01, 4.6783e-01, 2.5513e-01, 2.3157e-01],
         [7.8533e-01, 5.2832e-01, 7.1104e-01, 3.8385e-04],
         [4.1599e-01, 3.8450e-01, 8.8459e-01, 1.8808e-01]]),
 torch.float32)

In [9]:
# creating a random tensor of size (223, 224, 3)

random_image = torch.rand(size=(224, 224, 3))
random_image.shape, random_image.dtype

(torch.Size([224, 224, 3]), torch.float32)

Zeros and Ones

In [10]:
# ceateing a tensor with only zero values

zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [11]:
# ceateing a tensor with only 1

ones = torch.ones(size=(3,4))
ones, ones.dtype 

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [12]:
# creating a tensor with 1 in the diagonal

one_diag = torch.eye(4)
one_diag

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

CREATING A RANGE and TENSORS LIKE


Where:
* `start` = start of range (e.g. 0)
* `end` = end of range (e.g. 10)
* `step` = how many steps in between each value (e.g. 1)

In [13]:
# creating a range 
range = torch.arange(2,20,3)
range

tensor([ 2,  5,  8, 11, 14, 17])

In [14]:
zero_to_ten = torch.arange(start=1, end=10, step=1)
range_ten = torch.ones_like(input=zero_to_ten)
range_ten

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
float_32 = torch.tensor([1.,2.,3.,4.], dtype=None, device=None, requires_grad=False)

float_32, float_32.shape, float_32.dtype, float_32.device

(tensor([1., 2., 3., 4.]), torch.Size([4]), torch.float32, device(type='cpu'))

In [16]:
# creatin tensor with dtype=torch.float16 
float_16 =torch.tensor([2.,3.,4.,5.], dtype=torch.float16)
float_16.dtype

torch.float16

# Getting information from Tensors

In [17]:
# creating a tensor 
some_tensor = torch.rand(3,4)

# find out details about it 
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")
print(f"Tensor datatype: {some_tensor.dtype}")
print(f"Maximum number: {some_tensor.argmax()}")
print(f"Minimum number: {some_tensor.argmin()}")

tensor([[0.8408, 0.0108, 0.1556, 0.5020],
        [0.6620, 0.0626, 0.1008, 0.1642],
        [0.8921, 0.4991, 0.7183, 0.7145]])
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu
Tensor datatype: torch.float32
Maximum number: 8
Minimum number: 1


# Basic OPerations

In [18]:
# scalar addition 
tensor =torch.tensor([1.,2.,3.])
tensor + 10

tensor([11., 12., 13.])

In [19]:
# Multiply it by 10 - scalar multiplication
tensor * 10

tensor([10., 20., 30.])

In [20]:
# Scalar Subtraction
tensor - 10

tensor([-9., -8., -7.])

In [21]:
tensor * tensor

tensor([1., 4., 9.])

In [22]:
tensor @ tensor

tensor(14.)

In [23]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 175 μs


tensor(14.)

In [24]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

In [25]:
torch.manual_seed(42)

# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, out_features=6)

x = tensor_A
output = linear(x)

print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")


Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [26]:
x = torch.arange(1.,8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [29]:
# Add an extra dimension
x_reshaped = x.reshape(1,7)
x_reshaped.T

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.]])

In [28]:
# T0 change view 
z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [30]:
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

Stacking

In [34]:
x_stacked = torch.stack([x,x,x,x], dim=0) 
# lets change the dimension to 1
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [37]:
# Squeezing the tensor to only have dimension over 1 - torch.squeeze 
print(f"Previous tensor: {x_reshaped}")
print(f"Previous Shape: {x_reshaped.shape}")
print(f"Previous dimension: {x_reshaped.ndim}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")
print(f"New dimension: {x_squeezed.ndim}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous Shape: torch.Size([1, 7])
Previous dimension: 2

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])
New dimension: 1


Unsqueezing - to reverse squeezing  - torch.unsqueeze

In [41]:
x_squeezed = x_reshaped.squeeze()
print(f"\nPrevious tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")
print(f"Previous dimension: {x_squeezed.ndim}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")
print(f"New dimension: {x_unsqueezed.ndim}")


Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])
Previous dimension: 1

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])
New dimension: 2


Reordering the axes values with torch.permute()

In [42]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# permute the orignal tensor to rearrange the axis order
x_permuted = x_original.permute(1,2,0)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([224, 3, 224])


INDEXING - SELECTING DATA FROM TENSOR

In [46]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [47]:
# indexing values
# lets index bracket by bracket
print(f"First square: \n{x[0]}")
print(f"Second square: \n{x[0][0]}")
print(f"Third square: \n{x[0][0][0]}")

First square: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square: 
tensor([1, 2, 3])
Third square: 
1


In [48]:
# Getting Values from all dimension

x[:, 0]

tensor([[1, 2, 3]])

In [56]:
# get values of 0th and 1st dimensio

x[:,:,0]

tensor([[1, 4, 7]])

In [54]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [58]:
x[:,1,1]

tensor([5])

In [62]:
x[:,2,2]

tensor([9])

In [65]:
x[0,0,:]

tensor([1, 2, 3])

Pytorch Tensors and Numpy 

In [66]:
# torch.from_numpy(ndarray) - Numpy - Pytorch
# torch.Tensor.numpy() -Pytorch - Numpy

import numpy as np

In [68]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
tensor_np = torch.Tensor.numpy(tensor)
array, tensor, tensor_np

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))